site_name: Shorts Generator
site_description: Программа для автоматического создания YouTube Shorts из длинных видео.
site_author: Smart AutoClickers

theme:
  name: material

nav:
  - Главная: index.md
  - Руководство: manual.md


